name: Generate Contribution 3D

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "Github Actions Bot"

      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./config/3d-settings.json


      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Has Changes?
        id: git-check
        run: |
          if [[ -n $(git diff HEAD) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - if: steps.git-check.outputs.changes == 'true'
        name: Commit & Push
        run: |
          git add .
          git commit -m "Update 3D on ${{ steps.date.outputs.date }}
          Co-Authored-By: Ahmed Abdelbaset <A7med3bdulBaset@gmail.com>
          "
          git pull
          git push

      - if: steps.git-check.outputs.changes == 'false'
        name: Already Up-to-date 
        run: echo "No changes to push"
